--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "Schema"."MAIL_ACCOUNT" DROP CONSTRAINT "FK_MAIL_ACCOUNT_MAIL_HOST";

ALTER TABLE "Schema"."MAIL_JOB" DROP CONSTRAINT "FK_MAIL_JOB_MAIL_ACCOUNT";

ALTER TABLE "Schema"."MAIL_JOB" DROP CONSTRAINT "FK_MAIL_JOB_MAIL_USER";

ALTER TABLE "Schema"."MAIL_JOB_LOG" DROP CONSTRAINT "FK_MAIL_JOB_LOG_MAIL_JOB";

ALTER TABLE "Schema"."MAIL_JOB_REQUESTER" DROP CONSTRAINT "FK_MAIL_JOB_REQUESTER_MAIL_JOB";

ALTER TABLE "Schema"."MAIL_JOB_REQUESTER" DROP CONSTRAINT "FK_MAIL_JOB_REQUESTER_MAIL_REQUESTER";

ALTER TABLE "Schema"."MAIL_SEND_LOG" DROP CONSTRAINT "FK_MAIL_SEND_LOG_MAIL_ACCOUNT";

ALTER TABLE "Schema"."MAIL_SEND_LOG" DROP CONSTRAINT "FK_MAIL_SEND_LOG_MAIL_JOB_LOG";

ALTER TABLE "Schema"."MAIL_USER_PWD_HISTORY" DROP CONSTRAINT "FK_MAIL_USER_PWD_HISTORY_MAIL_USER";

ALTER TABLE "Schema"."MAIL_ACCOUNT" DROP CONSTRAINT "MAIL_ACCOUNT_PK";

ALTER TABLE "Schema"."MAIL_HOST" DROP CONSTRAINT "MAIL_HOST_PK";

ALTER TABLE "Schema"."MAIL_JOB" DROP CONSTRAINT "MAIL_JOB_PK";

ALTER TABLE "Schema"."MAIL_JOB_LOG" DROP CONSTRAINT "MAIL_RECEIVED_LOG_PK";

ALTER TABLE "Schema"."MAIL_JOB_REQUESTER" DROP CONSTRAINT "MAIL_JOB_REQUESTER_PK";

ALTER TABLE "Schema"."MAIL_REQUESTER" DROP CONSTRAINT "MAIL_REQUESTER_PK";

ALTER TABLE "Schema"."MAIL_SEND_LOG" DROP CONSTRAINT "MAIL_SEND_LOG_PK";

ALTER TABLE "Schema"."MAIL_USER" DROP CONSTRAINT "MAIL_USER_PK";

ALTER TABLE "Schema"."MAIL_USER_PWD_HISTORY" DROP CONSTRAINT "MAIL_USER_PWD_HISTORY_PK";

DROP TABLE "Schema"."MAIL_ACCOUNT";

DROP TABLE "Schema"."MAIL_HOST";

DROP TABLE "Schema"."MAIL_JOB";

DROP TABLE "Schema"."MAIL_JOB_LOG";

DROP TABLE "Schema"."MAIL_JOB_REQUESTER";

DROP TABLE "Schema"."MAIL_REQUESTER";

DROP TABLE "Schema"."MAIL_SEND_LOG";

DROP TABLE "Schema"."MAIL_USER";

DROP TABLE "Schema"."MAIL_USER_PWD_HISTORY";

DROP SCHEMA "Schema" RESTRICT;

CREATE SCHEMA "Schema";

CREATE TABLE "Schema"."MAIL_ACCOUNT" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"MOD_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"USERNAME" VARCHAR(50) NOT NULL, 
		"PASSWORD" VARCHAR(100) NOT NULL, 
		"MAIL_HOST_ID" INTEGER NOT NULL, 
		CONSTRAINT "MAIL_ACCOUNT_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_HOST" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"MOD_DAT" TIMESTAMP(4) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"URL" VARCHAR(1024) NOT NULL, 
		"ACTIVE_FLAG" SMALLINT NOT NULL DEFAULT 0, 
		"ACHIVED_FLAG" SMALLINT NOT NULL DEFAULT 0, 
		CONSTRAINT "MAIL_HOST_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_JOB" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"REQ_JSON" CLOB(10240) NOT NULL, 
		"MAIL_USER_ID" INTEGER NOT NULL, 
		"MAILL_ACCOUNT_ID" INTEGER NOT NULL, 
		CONSTRAINT "MAIL_JOB_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_JOB_LOG" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6), 
		"START_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"END_DAT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP(6), 
		"STATE" VARCHAR(50) NOT NULL, 
		"MAIL_JOB_ID" INTEGER NOT NULL, 
		CONSTRAINT "MAIL_RECEIVED_LOG_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_JOB_REQUESTER" (
		"MAIL_JOB_ID" INTEGER NOT NULL, 
		"MAIL_REQUESTER_ID" INTEGER NOT NULL, 
		CONSTRAINT "MAIL_JOB_REQUESTER_PK" PRIMARY KEY
		("MAIL_JOB_ID", 
		 "MAIL_REQUESTER_ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_REQUESTER" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"IPV4" VARCHAR(15), 
		"IPV6" VARCHAR(50), 
		CONSTRAINT "MAIL_REQUESTER_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_SEND_LOG" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"SEND_DAT" TIMESTAMP, 
		"EMAIL_ADDRESS" VARCHAR(100) NOT NULL, 
		"FILE_KEY" VARCHAR(5) NOT NULL, 
		"MAIL_ACCOUNT_ID" INTEGER NOT NULL, 
		"MAIL_JOB_LOG" INTEGER NOT NULL, 
		CONSTRAINT "MAIL_SEND_LOG_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_USER" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"MOD_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"USERNAME" VARCHAR(20) NOT NULL, 
		"PASSWORD" VARCHAR(1024) NOT NULL, 
		CONSTRAINT "MAIL_USER_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

CREATE TABLE "Schema"."MAIL_USER_PWD_HISTORY" (
		"ID" INTEGER NOT NULL, 
		"CRE_DAT" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(6), 
		"PASSWORD" VARCHAR(1024) NOT NULL, 
		"MAIL_USER_ID" INTEGER NOT NULL, 
		CONSTRAINT "MAIL_USER_PWD_HISTORY_PK" PRIMARY KEY
		("ID")
	)
	DATA CAPTURE NONE 
	COMPRESS NO;

ALTER TABLE "Schema"."MAIL_ACCOUNT" ADD CONSTRAINT "FK_MAIL_ACCOUNT_MAIL_HOST" FOREIGN KEY
	("MAIL_HOST_ID")
	REFERENCES "Schema"."MAIL_HOST"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_JOB" ADD CONSTRAINT "FK_MAIL_JOB_MAIL_ACCOUNT" FOREIGN KEY
	("MAILL_ACCOUNT_ID")
	REFERENCES "Schema"."MAIL_ACCOUNT"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_JOB" ADD CONSTRAINT "FK_MAIL_JOB_MAIL_USER" FOREIGN KEY
	("MAIL_USER_ID")
	REFERENCES "Schema"."MAIL_USER"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_JOB_LOG" ADD CONSTRAINT "FK_MAIL_JOB_LOG_MAIL_JOB" FOREIGN KEY
	("MAIL_JOB_ID")
	REFERENCES "Schema"."MAIL_JOB"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_JOB_REQUESTER" ADD CONSTRAINT "FK_MAIL_JOB_REQUESTER_MAIL_JOB" FOREIGN KEY
	("MAIL_JOB_ID")
	REFERENCES "Schema"."MAIL_JOB"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_JOB_REQUESTER" ADD CONSTRAINT "FK_MAIL_JOB_REQUESTER_MAIL_REQUESTER" FOREIGN KEY
	("MAIL_REQUESTER_ID")
	REFERENCES "Schema"."MAIL_REQUESTER"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_SEND_LOG" ADD CONSTRAINT "FK_MAIL_SEND_LOG_MAIL_ACCOUNT" FOREIGN KEY
	("MAIL_ACCOUNT_ID")
	REFERENCES "Schema"."MAIL_ACCOUNT"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_SEND_LOG" ADD CONSTRAINT "FK_MAIL_SEND_LOG_MAIL_JOB_LOG" FOREIGN KEY
	("MAIL_JOB_LOG")
	REFERENCES "Schema"."MAIL_JOB_LOG"
	("ID")
	ON DELETE CASCADE;

ALTER TABLE "Schema"."MAIL_USER_PWD_HISTORY" ADD CONSTRAINT "FK_MAIL_USER_PWD_HISTORY_MAIL_USER" FOREIGN KEY
	("MAIL_USER_ID")
	REFERENCES "Schema"."MAIL_USER"
	("ID")
	ON DELETE CASCADE;

